CREATE TABLE CATEGORII
(
    CATEGORIE_ID NUMBER(5) PRIMARY KEY,
    NUME         VARCHAR2(60) NOT NULL
);

CREATE TABLE AUTORI
(
    AUTOR_ID NUMBER(5) PRIMARY KEY,
    NUME     VARCHAR2(30) NOT NULL,
    ACTIV    NUMBER(1)    NOT NULL
);

CREATE TABLE STATUSURI
(
    STATUS_ID NUMBER(5) PRIMARY KEY,
    NUME      VARCHAR2(15) NOT NULL,
    ASCUNS    NUMBER(1)    NOT NULL
);

CREATE TABLE ARTICOLE
(
    ARTICOL_ID   NUMBER(5) PRIMARY KEY,
    CATEGORIE_ID NUMBER(5)     NOT NULL,
    AUTOR_ID     NUMBER(5)     NOT NULL,
    STATUS_ID    NUMBER(5)     NOT NULL,
    SURSA_ID     NUMBER(5)     NOT NULL,
    DATA         DATE          NOT NULL,
    TITLU        VARCHAR2(100) NOT NULL,
    CONTINUT     CLOB,
    LINK_IMAGINE VARCHAR2(200)
);

CREATE TABLE COMENTARII
(
    COMENTARIU_ID NUMBER(5) PRIMARY KEY,
    ARTICOL_ID    NUMBER(5)     NOT NULL,
    NUME_USER     VARCHAR2(15)  NOT NULL,
    CONTINUT      VARCHAR2(300) NOT NULL
);
CREATE TABLE SURSE
(
    SURSA_ID NUMBER(5) PRIMARY KEY,
    NUME     VARCHAR2(100) NOT NULL
);


ALTER TABLE ARTICOLE
    ADD CONSTRAINT CATEGORIE_FK FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORII (CATEGORIE_ID);

ALTER TABLE ARTICOLE
    ADD CONSTRAINT AUTOR_FK FOREIGN KEY (AUTOR_ID) REFERENCES AUTORI (AUTOR_ID);

ALTER TABLE ARTICOLE
    ADD CONSTRAINT STATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES STATUSURI (STATUS_ID);

ALTER TABLE ARTICOLE
    ADD CONSTRAINT SURSA_FK FOREIGN KEY (SURSA_ID) REFERENCES SURSE (SURSA_ID);

ALTER TABLE COMENTARII
    ADD CONSTRAINT ARTICOL_FK FOREIGN KEY (ARTICOL_ID) REFERENCES ARTICOLE (ARTICOL_ID);

ALTER TABLE STATUSURI
    ADD CONSTRAINT ASCUNS_CK CHECK ( ASCUNS IN (0, 1) );

ALTER TABLE AUTORI
    ADD CONSTRAINT ACTIV_CK CHECK ( ACTIV IN (0, 1) );
