DROP TABLE AUTORI CASCADE CONSTRAINTS;
DROP TABLE CATEGORII CASCADE CONSTRAINTS;
DROP TABLE ARTICOLE CASCADE CONSTRAINTS;
DROP TABLE STATUSURI CASCADE CONSTRAINTS;
DROP TABLE COMENTARII CASCADE CONSTRAINTS;
DROP TABLE SURSE CASCADE CONSTRAINTS
