DROP TABLE AUTORI CASCADE CONSTRAINTS;
DROP TABLE CATEGORII CASCADE CONSTRAINTS;
DROP TABLE TIPURI_CONTINUT CASCADE CONSTRAINTS;
DROP TABLE ARTICOLE CASCADE CONSTRAINTS;
DROP TABLE CONTINUTURI CASCADE CONSTRAINTS;
DROP TABLE STATUSURI CASCADE CONSTRAINTS;
