SELECT SURSE.NUME, AUTORI.NUME, STATUSURI.NUME, CATEGORII.NUME, ARTICOLE.TITLU
  FROM ARTICOLE, AUTORI, CATEGORII, STATUSURI, SURSE
 WHERE
       AUTORI.AUTOR_ID = ARTICOLE.AUTOR_ID
   AND ARTICOLE.CATEGORIE_ID = CATEGORII.CATEGORIE_ID
   AND ARTICOLE.STATUS_ID = STATUSURI.STATUS_ID
   AND ARTICOLE.SURSA_ID = SURSE.SURSA_ID
   AND ARTICOLE.STATUS_ID = STATUSURI.STATUS_ID;

SELECT *
  FROM ARTICOLE A, CATEGORII C
 WHERE
         A.CATEGORIE_ID = C.CATEGORIE_ID(+)
 ORDER BY C.CATEGORIE_ID
 FETCH FIRST 5 ROWS ONLY;
