SELECT SURSE.NUME, AUTORI.NUME, STATUS.NUME, CATEGORII.NUME, ARTICOLE.TITLU
FROM ARTICOLE,
     AUTORI,
     CATEGORII,
     STATUS,
     SURSE
WHERE AUTORI.AUTOR_ID = ARTICOLE.AUTOR_ID
  AND ARTICOLE.CATEGORIE_ID = CATEGORII.CATEGORIE_ID
  AND ARTICOLE.STATUS_ID = STATUS.STATUS_ID
  AND ARTICOLE.SURSA_ID = SURSE.SURSA_ID
  AND ARTICOLE.STATUS_ID = STATUS.STATUS_ID;

SELECT *
FROM ARTICOLE A,
     CATEGORII C
WHERE A.CATEGORIE_ID = C.CATEGORIE_ID(+)
ORDER BY C.CATEGORIE_ID
FETCH FIRST 5 ROWS ONLY;

SELECT count(*)
FROM SURSE,
     STATUS
WHERE SURSE.STATUS_ID = STATUS.STATUS_ID
  AND STATUS.NUME = upper('activ');


SELECT TITLU, CONTINUT, AUTORI.NUME
FROM ARTICOLE,
     AUTORI
WHERE ARTICOLE.AUTOR_ID = AUTORI.AUTOR_ID
ORDER BY AUTORI.NUME;