CREATE TABLE CATEGORII
(
    CATEGORIE_ID NUMBER(5) PRIMARY KEY,
    NUME         VARCHAR2(15) NOT NULL
);
CREATE TABLE AUTORI
(
    AUTOR_ID NUMBER(5) PRIMARY KEY,
    NUME     VARCHAR2(15) NOT NULL,
    PRENUME  VARCHAR2(15) NOT NULL
);
CREATE TABLE STATUSURI
(
    STATUS_ID NUMBER(5) PRIMARY KEY,
    NUME      VARCHAR2(15) NOT NULL,
    ASCUNS    NUMBER(1)    NOT NULL
);
CREATE TABLE ARTICOLE
(
    ARTICOL_ID   NUMBER(5) PRIMARY KEY,
    CATEGORIE_ID NUMBER(5)     NOT NULL,
    AUTOR_ID     NUMBER(5)     NOT NULL,
    STATUS_ID    NUMBER(5)     NOT NULL,
    DATA         DATE          NOT NULL,
    TITLU        VARCHAR2(100) NOT NULL
);
CREATE TABLE TIPURI_CONTINUT
(
    TIP_ID NUMBER(5) PRIMARY KEY,
    NUME   VARCHAR2(15) NOT NULL -- paragraf sau imagine
);
CREATE TABLE CONTINUTURI
(
    ARTICOL_ID      NUMBER(5) NOT NULL,
    CONTINUT_ORDINE NUMBER(5) NOT NULL, -- ordinea continutului in articol
    TIP_ID          NUMBER(5) NOT NULL,
    CONTINUT        CLOB,
    SURSA           VARCHAR2(100)
);

ALTER TABLE ARTICOLE
    ADD CONSTRAINT CATEGORIE_FK FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORII (CATEGORIE_ID);
ALTER TABLE ARTICOLE
    ADD CONSTRAINT AUTOR_FK FOREIGN KEY (AUTOR_ID) REFERENCES AUTORI (AUTOR_ID);
ALTER TABLE ARTICOLE
    ADD CONSTRAINT STATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES STATUSURI (STATUS_ID);
ALTER TABLE CONTINUTURI
    ADD CONSTRAINT CONTINUT_PK PRIMARY KEY (ARTICOL_ID, CONTINUT_ORDINE);
ALTER TABLE CONTINUTURI
    ADD CONSTRAINT ARTICOL_FK FOREIGN KEY (ARTICOL_ID) REFERENCES ARTICOLE (ARTICOL_ID);
ALTER TABLE CONTINUTURI
    ADD CONSTRAINT TIP_FK FOREIGN KEY (TIP_ID) REFERENCES TIPURI_CONTINUT (TIP_ID);
ALTER TABLE STATUSURI
    ADD CONSTRAINT ASCUNS_CK CHECK ( ASCUNS IN (0, 1) );
